config/routes.rb
Rails.application.routes.draw do
  root 'landing#index', via: :get

  resources :recipes, only: [:show, :new, :create]
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to root_path
    else
      flash.now[:error] = 'Could not publish recipe!'
      render action: 'new'
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.haml
%h1 Recipe Site

= link_to 'New Recipe', new_recipe_path

%h2 Latest Recipes

- @recipes.each do |recipe|
  = link_to recipe.title, recipe
  %p= recipe.description

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/new.html.haml
= form_for(@recipe) do |form|
  = form.label :title
  = form.text_field :title
  = form.label :description
  = form.text_area :description
  = form.submit 'Publish Recipe'